---
deployment:
  tasks:
    - export DEPLOYPATH=/home/michael3/public_html
    - /bin/cp public/index.html $DEPLOYPATH
    - /bin/cp public/landing.html $DEPLOYPATH
    - /bin/cp public/generic.html $DEPLOYPATH
    - /bin/cp public/css/ $DEPLOYPATH
    - /bin/cp public/js/ $DEPLOYPATH
    - /bin/cp public/img/ $DEPLOYPATH